name = "example"
version = "1.0.0"
description = "Example using honk to validate xyz.statusphere.status records from Jetstream"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
honk = { path = ".." }
goose = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
