name = "honk"
version = "1.0.0"
description = "ATProtocol lexicon validator for Gleam"
internal_modules = ["honk/internal", "honk/internal/*"]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
gleam_time = ">= 1.5.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
