name = "honk"
version = "1.2.0"
description = "ATProtocol lexicon validator for Gleam"
internal_modules = ["honk/internal", "honk/internal/*"]
licences = ["Apache-2.0"]
repository = { type = "github", user = "bigmoves", repo = "honk" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
gleam_time = ">= 1.5.0 and < 2.0.0"
simplifile = ">= 2.3.1 and < 3.0.0"
argv = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
